format = """
[ ](fg:foam) \
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

add_newline = false
palette = "rose-pine"

[directory]
style = "fg:rose"
read_only_style = "fg:rose"
truncation_length = 1
format = "[$path]($style) "

[git_branch]
style = "fg:pine"
symbol = " "
format = '[git:\([$branch](fg:love)\)]($style)'

[character]
success_symbol = '[ ✗](bold gold)'
error_symbol = '[ ✗](bold love)'

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
